import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';
import { format, subDays } from 'npm:date-fns';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Get weekly stats
    const completions = await base44.entities.CompletionLog.list('-created_date', 100);
    const achievements = await base44.entities.Achievement.list('-earned_date', 10);
    
    const today = format(new Date(), 'yyyy-MM-dd');
    const weekAgo = format(subDays(new Date(), 7), 'yyyy-MM-dd');
    
    const weeklyCompletions = completions.filter(c => 
      c.completion_date >= weekAgo && c.completion_date <= today
    );

    const totalTime = weeklyCompletions.reduce((sum, c) => sum + (c.time_spent_minutes || 0), 0);

    // Get Gmail access token
    const accessToken = await base44.asServiceRole.connectors.getAccessToken('gmail');

    // Create email content
    const emailHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #8b5cf6;">🎯 Your Weekly Progress Report</h2>
        <p>Hi ${user.full_name || 'Champion'},</p>
        <p>Here's your productivity summary for the week:</p>
        
        <div style="background: linear-gradient(135deg, #8b5cf6 0%, #ec4899 100%); padding: 20px; border-radius: 10px; color: white; margin: 20px 0;">
          <h3 style="margin: 0 0 15px 0;">📊 This Week's Stats</h3>
          <p style="margin: 5px 0;">✅ Completed Tasks: <strong>${weeklyCompletions.length}</strong></p>
          <p style="margin: 5px 0;">⏱️ Time Invested: <strong>${Math.floor(totalTime / 60)}h ${totalTime % 60}m</strong></p>
          <p style="margin: 5px 0;">🏆 Total XP: <strong>${user.total_xp || 0}</strong></p>
          <p style="margin: 5px 0;">💎 Gems Earned: <strong>${user.gems || 0}</strong></p>
        </div>

        <p>Keep up the great work! 🚀</p>
        <p style="color: #666; font-size: 12px;">Generated by Routine Quest</p>
      </div>
    `;

    const message = [
      'Content-Type: text/html; charset=utf-8',
      'MIME-Version: 1.0',
      `To: ${user.email}`,
      `From: Routine Quest <noreply@routinequest.app>`,
      'Subject: Your Weekly Routine Quest Progress Report',
      '',
      emailHtml
    ].join('\n');

    const encodedMessage = btoa(unescape(encodeURIComponent(message)))
      .replace(/\+/g, '-')
      .replace(/\//g, '_')
      .replace(/=+$/, '');

    const response = await fetch('https://gmail.googleapis.com/gmail/v1/users/me/messages/send', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ raw: encodedMessage }),
    });

    if (!response.ok) {
      const error = await response.text();
      throw new Error(`Gmail API error: ${error}`);
    }

    return Response.json({ success: true, message: 'Email sent successfully!' });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});